# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/hdd/dev/qgis/fpd_processor/fpd_processor_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FpdProcessorDockWidgetBase(object):
    def setupUi(self, FpdProcessorDockWidgetBase):
        FpdProcessorDockWidgetBase.setObjectName("FpdProcessorDockWidgetBase")
        FpdProcessorDockWidgetBase.resize(395, 785)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.request_label = QtWidgets.QLabel(self.dockWidgetContents)
        self.request_label.setObjectName("request_label")
        self.gridLayout.addWidget(self.request_label, 0, 0, 1, 1)
        self.mFeatureListComboBox = gui.QgsFeatureListComboBox(self.dockWidgetContents)
        self.mFeatureListComboBox.setObjectName("mFeatureListComboBox")
        self.gridLayout.addWidget(self.mFeatureListComboBox, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.createCartogramButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.createCartogramButton.setObjectName("createCartogramButton")
        self.gridLayout.addWidget(self.createCartogramButton, 3, 0, 1, 1)
        self.createFormButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.createFormButton.setObjectName("createFormButton")
        self.gridLayout.addWidget(self.createFormButton, 2, 0, 1, 1)
        FpdProcessorDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(FpdProcessorDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(FpdProcessorDockWidgetBase)

    def retranslateUi(self, FpdProcessorDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        FpdProcessorDockWidgetBase.setWindowTitle(_translate("FpdProcessorDockWidgetBase", "Обработка запросов в ФПД"))
        self.request_label.setText(_translate("FpdProcessorDockWidgetBase", "Заявление"))
        self.createCartogramButton.setText(_translate("FpdProcessorDockWidgetBase", "Создать картограмму"))
        self.createFormButton.setText(_translate("FpdProcessorDockWidgetBase", "Сформировать заявление"))
from qgis import gui
